[package]
name = "spark-matcher"
description = "A Rust version of the spark-matcher project."
version = "0.1.0"
edition = "2021"
authors = ["Oleksii Kshenskyi <oleksii.kshenskyi@uatechpeople.com>"]
license = "Apache-2.0"

[dependencies]
fuels = { version = "0.55.0", features = ["fuel-core-lib"] }
rand = "0.8.5"
tokio = { version = "1.12", features = ["rt", "macros"] }
src20_sdk = { git = "https://github.com/compolabs/src-20.git", branch = "master" }
orderbook = { git = "https://github.com/compolabs/orderbook-contract.git", branch = "master" }
dotenv = "0.15.0"
hex = "0.4"
axum = {version = "0.7.5" }
anyhow = "1.0.82"
reqwest = { version = "0.12.4", features = ["json"] }
serde_json = "1.0.116"
serde = { version = "1.0.198", features = ["derive"] }

[[bin]]
name = "spark-matcher"
path = "src/main.rs"
