version: '3.8'
services:
  spark-matcher:
    build: .
    ports:
      - "5003:5003"
    environment:
     - PRIVATE_KEY=${PRIVATE_KEY}
     - CONTRACT_ID=${CONTRACT_ID}
     - INDEXER_URL_NO_ORDER_TYPE=${INDEXER_URL_NO_ORDER_TYPE}
    restart: unless-stopped